    # F:\chinar\render.yaml
    # This file defines services for Render.com deployment

    services:
      # Web Service for your Django App
      - type: web
        name: chinar-app
        env: python
        buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
        startCommand: "gunicorn chinar_project.wsgi:application --log-file -"
        healthCheckPath: /admin/login/
        envVars:
          - key: DATABASE_URL
            fromDatabase: chinar_db # Use fromDatabase for simpler linking to blueprint-defined database
          - key: SECRET_KEY
            generateValue: true
          - key: DEBUG
            value: "False"
          - key: WEB_CONCURRENCY
            value: 1
        autoDeploy: true

      # PostgreSQL Database Service
      - type: pserv
        name: chinar_db
        plan: free
        # No other properties like buildCommand, startCommand, healthCheckPath, envVars, or runtime
        # are needed or allowed for a simple pserv (managed database service).
        # This minimal definition is correct.
    